# Generated by Django 4.2.4 on 2023-08-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_code', models.CharField(max_length=15)),
                ('high', models.DecimalField(decimal_places=1, max_digits=6)),
                ('low', models.DecimalField(decimal_places=1, max_digits=6)),
                ('open', models.DecimalField(decimal_places=1, max_digits=6)),
                ('close', models.DecimalField(decimal_places=1, max_digits=6)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
